### ISSUE TITLE
Hi 我想知道 现在ifttt是不是还是有30M的限制 以及 有时候会出现些问题

### ISSUE THREAD

**Issue by BlingRbt** [gonejack/tumblr-images-memcached#1]
Hi 我想知道 现在ifttt是不是还是有30M的限制 以及 有时候会出现些问题 比如 视频无法下载 like之后 dropbox会出现图片 文件未找到 还有就是 ifttt 运行不及时（？  这个问题是ifttt的吗
还有就是如果if有30m大小限制 那请问一下有没有办法能突破限制呢？ p.s:我自己有台服务器 就是延迟感人...

**Comment by BlingRabbit** [comment]
Hi 我想知道 现在ifttt是不是还是有30M的限制 以及 有时候会出现些问题 比如 视频无法下载 like之后 dropbox会出现图片 文件未找到 还有就是 ifttt 运行不及时（？  这个问题是ifttt的吗
还有就是如果if有30m大小限制 那请问一下有没有办法能突破限制呢？ p.s:我自己有台服务器 就是延迟感人...

**Comment by gonejack** [comment]
ifttt太渣我也是什么都做不了，实在让人心累。

现在自己都不用了，写了个脚本在本地跑下载红心。

可能有空有心情时会写写完全在服务器跑的程序，不依赖ifttt，到时候看能否放上GAE上去跑。
