### ISSUE TITLE
请问一下VPS如何配置这个服务？

### ISSUE THREAD

**Issue by OHLIA** [gonejack/tumblr-images-memcached#11]
想知道在VPS下配置使用，
具体过程是否一样？

**Comment by gonejack** [comment]
VPS的话是配置PHP服务的操作，一般都是类似这样的流程https://cloud.tencent.com/document/product/213/2128
但不建议VPS上用，VPS的网络一般都比GAE差不少。

**Comment by OHLIA** [comment]
我现在用宝塔面板装好LNMP了，用的PHP71版本，
开了网站。
把文件都拷贝到VPS的对应网站目录上了。
请问一下接下来要怎么做？

**Comment by gonejack** [comment]
访问一下

```
域名/main.php
```

**Comment by OHLIA** [comment]
显示 Hello,tumblr, 表示成功了吧？

然后再IFTTT里面创建的APPLET的File URL里面输入： 
域名/fetch.php?url={{Url}}

但是我发现网站目录里面并没有fetch.php这个文件，这个文件是自己会生成吗？

推送不了，applet也显示不可运行。

**Comment by gonejack** [comment]
填main.php，自己用的服务器的话就用main.php。

IFTTT里的fetch.php是我另写的一个分发脚本，因为一个服务器撑不起。

**Comment by OHLIA** [comment]
我刚改了，有推送文件到网盘，但是有点问题：
1.文件名字是按Applet里面设定的，但是没有后缀名；
2.两个文件都是1KB，用编辑器打开显示：
`Warning: include_once(memcached.php): failed to open stream: No such file or directory in /www/wwwroot/tt.newlia.tk/main.php on line 15

Warning: include_once(): Failed opening 'memcached.php' for inclusion (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/tt.newlia.tk/main.php on line 15

Fatal error: Uncaught Error: Class 'Memcached' not found in /www/wwwroot/tt.newlia.tk/mc.php:16 Stack trace: #0 /www/wwwroot/tt.newlia.tk/main.php(42): mc->__construct() #1 /www/wwwroot/tt.newlia.tk/main.php(18): main(false, 4, false) #2 {main} thrown in /www/wwwroot/tt.newlia.tk/mc.php on line 16`

**Comment by OHLIA** [comment]
我刚改了，有推送文件到网盘，但是有点问题：
1.文件名字是按Applet里面设定的，但是没有后缀名；
2.两个文件都是1KB，用编辑器打开显示：

Warning: include_once(memcached.php): failed to open stream: No such file or directory in /www/wwwroot/域名/main.php on line 15

Warning: include_once(): Failed opening 'memcached.php' for inclusion (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/域名/main.php on line 15

Fatal error: Uncaught Error: Class 'Memcached' not found in /www/wwwroot/域名/mc.php:16 Stack trace: #0 /www/wwwroot/域名/main.php(42): mc->__construct() #1 /www/wwwroot/域名/main.php(18): main(false, 4, false) #2 {main} thrown in /www/wwwroot/域名/mc.php on line 16

**Comment by OHLIA** [comment]
我解决了，在宝塔面板PHP设置里安装memcached就行了，
非常感谢作者的帮助。

**Comment by liubangjain** [comment]
> 我刚改了，有推送文件到网盘，但是有点问题：
> 1.文件名字是按Applet里面设定的，但是没有后缀名；
> 2.两个文件都是1KB，用编辑器打开显示：
> 
> Warning: include_once(memcached.php): failed to open stream: No such file or directory in /www/wwwroot/域名/main.php on line 15
> 
> Warning: include_once(): Failed opening 'memcached.php' for inclusion (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/域名/main.php on line 15
> 
> Fatal error: Uncaught Error: Class 'Memcached' not found in /www/wwwroot/域名/mc.php:16 Stack trace: #0 /www/wwwroot/域名/main.php(42): mc->__construct() #1 /www/wwwroot/域名/main.php(18): main(false, 4, false) #2 {main} thrown in /www/wwwroot/域名/mc.php on line 16

请问，没有后缀是如何解决的呢？

**Comment by gonejack** [comment]
@liubangjain 正常情况下是有后缀的，可以查看一下文件内容，看是不是程序的报错信息。
