### ISSUE TITLE
推送的文件没有后缀名

### ISSUE THREAD

**Issue by OHLIA** [gonejack/tumblr-images-memcached#12]
搞好VPS自建推送服务器，
发现推送的文件没有后缀名。
https://s1.ax2x.com/2018/02/10/y3Hvn.jpg

**Comment by gonejack** [comment]
检查一下是不是IFTTT配置错误了。

**Comment by OHLIA** [comment]
File url:域名/main.php?url=
File name:Blogname-time

**Comment by gonejack** [comment]
直接浏览器访问
```
域名/main.php?url=tumblr帖子地址
```
如果跳转的地址正常的话，那就没有办法了，不是 ifttt 就是 onedrive 的问题

**Comment by OHLIA** [comment]
自己手动的链接可以下回有后缀名的文件，
多图的时候，有时候下回来html文件，里面是各个图片的下载链接，这是正常的吗？

**Comment by gonejack** [comment]
是正常的，因为服务器负担大不打包下载一些特大的GIF图了，你自己服务器用的话可以按 ReadMe 更改。
