### ISSUE TITLE
输出的压缩包命名含有windows 不兼容的字符

### ISSUE THREAD

**Issue by shijunyi** [gonejack/tumblr-images-memcached#13]
你好，
使用你的代码配置了GAE，但是输出的压缩包命名是  2018-03-06T12:40:07.224Z.zip 。
该命名含有 `：`  为windows 文件名不兼容的字符，使得Dropbox 不能自动同步到windows 上。
请问 修改哪个位置的代码，可输出类似于 2018-03-06 124007.zip 。
谢谢。

**Comment by gonejack** [comment]
这个是考虑过的，代码里写的是这个：

```
header('Content-Disposition: attachment; filename=' . date('Y-M-j-D-G-i-s') . '.zip');
```

但可以被IFTTT忽略，可以检查一下IFTTT配置，应该是那边的问题。

**Comment by shijunyi** [comment]
谢谢回复，确实IFTTT 和Dropbox的锅，直接在浏览器 就没问题。
