### ISSUE TITLE
您好，我想把您这个脚本放到vps上跑，因为GAE有每天1G的限制，但总是报500错误。

### ISSUE THREAD

**Issue by yanyuechuixue** [gonejack/tumblr-images-memcached#4]
我是这么做的，git clone 到nginx（lnmp装好） 的根目录，然后访问 http://xxx.xxx/main.php ，输出 Hello Tumblr !

但是我访问 http://xxx.xxx/main.php?url=http://xxx.tumblr.com/post/1111111  的时候，就会报500错误。

请问这个该修改哪里？

**Comment by yanyuechuixue** [comment]
找到了，谢谢！

**Comment by OHLIA** [comment]
请问一下，你后面是怎么解决的？
