### ISSUE TITLE
可以编写一个twitter的规则吗？

### ISSUE THREAD

**Issue by queyalaolang** [gonejack/tumblr-images-memcached#5]
可以编写一个类似这样的规则，就是twitter点赞的视频自动保存到google drive吗？谢谢

**Comment by gonejack** [comment]
我从Tumblr出来就喜欢Tumblr，是Tumblr的重度用户。

但对Twitter就没什么太大兴趣了。

**Comment by queyalaolang** [comment]
非常感谢你写的tumblr规则，谢谢




发自网易邮箱大师
在2017年04月20日 23:28，John Youi 写道：

我从Tumblr出来就喜欢Tumblr，是Tumblr的重度用户才写的这些。

但对Twitter就没什么太大兴趣了。
