### ISSUE TITLE
备份到的Dropbox的视频文件变成aac后缀名的音频文件了

### ISSUE THREAD

**Issue by liubangjain** [gonejack/tumblr-images-memcached#8]
备份到的Dropbox的视频文件变成aac后缀名的音频文件了，请问是我配置的问题，还是其他问题？有解决方法吗？

**Comment by gonejack** [comment]
能否附上帖子地址，排查一下原因

**Comment by OHLIA** [comment]
我推送到onedrive for business 也是acc格式，不过用POTplayer可以正常播放
