### ISSUE TITLE
关于图片如何修改为不打包

### ISSUE THREAD

**Issue by windy1lee** [gonejack/tumblr-images-memcached#9]
如题，利用代码已经可以运行，
但like的图片上传到dropbox的为zip格式。
如何设置成直接上传JPG格式的图片！！！

**Comment by gonejack** [comment]
多张图是要打包的，这是dropbox跟ifttt的问题，没有办法。

**Comment by OHLIA** [comment]
请问可否修改成多图发送到telegram？

**Comment by gonejack** [comment]
@OHLIA 这个太夸张了，不太可能。
